### ISSUE TITLE
calculate percentages for only one known hand

### ISSUE THREAD

**Issue by DerKorb** [siavashg87/poker-odds-calc#4]
I would like to calculate the odds for combinations without knowing opponent hands. This should probably only require to remove the check?

**Comment by siavashg87** [comment]
The odds is calculation of one hand against one or several other hand(s). Having one hand will always result in 100% win as there is nothing to campare to.

**Comment by DerKorb** [comment]
That statement would be true if you only calculate the odds of winning. You do however also calculate the odds to get a certain hand.

**Comment by siavashg87** [comment]
We calculate the odds of possible boards, not possible hands.

**Comment by DerKorb** [comment]
Well maybe I understood this wrong, but for me it looks like I could say: given my hand and a flop, how probable is it for me to get a flush. This information would be useful to me, even if I do not know any of my opponent hands.
